In [8]:
import pandas.util.testing as tm

In [14]:
tm._N, tm._K = 15, 3

In [15]:
import numpy as np

In [16]:
np.random.seed(444)

In [17]:
tm.makeTimeDataFrame(freq='M')

                   A         B         C         D
2000-01-31  0.357440  0.266873  0.353728 -0.536561
2000-02-29  0.377538 -0.480331 -0.433926 -0.886787
2000-03-31  1.382338  0.300781 -0.498028  0.107101
2000-04-30  1.175549 -0.179054  0.228771 -0.740890
2000-05-31 -0.939276  1.183669 -0.650078 -0.075697
2000-06-30 -1.143150 -0.110787  0.467718  0.472508
2000-07-31 -0.542440  0.308326 -0.978244  0.433292
2000-08-31 -0.548708  1.788076  1.622561 -1.145501
2000-09-30  0.208520 -2.392712  0.943451  1.959270
2000-10-31  0.212690  0.626777  0.645811  0.433279
2000-11-30  1.268021  0.027123 -2.439433  1.542175
2000-12-31 -0.807303 -0.171530 -0.369971  0.833122
2001-01-31 -3.303072  1.415373 -1.083235  1.277340
2001-02-28 -0.806650 -0.913075  1.666211 -0.714293
2001-03-31 -0.360329 -0.648337  0.811157 -0.126947
2001-04-30 -0.880396 -0.622768 -1.162884  1.111996
2001-05-31  0.152631 -0.200700 -1.364761  0.807430
2001-06-30  0.250250 -0.016981  0.073522 -0.044810
2001-07-31  0.078508 -1.580155 -0.158240 -0.311915
2001-08-31 -0.903904 -1.272956  1.309005 -1.121644
2001-09-30  0.493282 -1.771348 -1.621449 -0.889349
2001-10-31  1.753644 -0.002065 -1.223276  0.633046
2001-11-30  0.574751 -0.945969  0.258372 -1.239643
2001-12-31 -0.031397  0.928850  0.540705 -0.349969
2002-01-31  0.697150  2.435089 -0.210238 -1.029196
2002-02-28  0.810017  0.904235 -0.824710  1.425119
2002-03-31  0.086494  1.454279  1.009086  0.920277
2002-04-30  0.260619  0.571817  0.605740 -0.472858
2002-05-31 -0.761182 -0.329118  0.348214 -0.058525
2002-06-30  0.686478  0.012958 -0.139900  0.151168